### ISSUE TITLE
Dockerfile - ( `runDepts` ) only on build

### ISSUE THREAD

**Issue by valentinab25** [RedTurtle/design-volto-theme#401]
Hello

I was reviewing your Dockerfile after your plone conf presentation. I noticed that you have the `runDeps` installed only on the build image.

https://github.com/RedTurtle/design-volto-theme/blob/master/Dockerfile#L9

You should copy the `runDeps` installation to the main image ( https://github.com/RedTurtle/design-volto-theme/blob/master/Dockerfile#L20) . 

Thanks
Valentina

**Comment by pnicolli** [comment]
Thanks @valentinab25 
After a thorough check, that runDeps definition was a leftover from a copypaste :) there are no needed runDeps, the Dockerfile is fixed, see [the latest one](https://github.com/RedTurtle/design-volto-theme/blob/master/Dockerfile).
